const express = require('express');
const mysql = require('mysql2/promise');
const path = require('path');
const fs = require('fs');
require('dotenv').config();

const app = express();

// Setting up EJS so i can quickly render HTML without a separate React frontend
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));
app.use(express.urlencoded({ extended: true })); // Needed for Question 3's form submission

// Create the Aiven MySQL Connection Pool
const pool = mysql.createPool({
    uri: process.env.DATABASE_URL,
        ssl: {
                rejectUnauthorized: false
                            }
                            });

                            // Homepage Route
                app.get('/', (req, res) => {
                  res.render('index');
                });

// Question 1: Display result for any individual polling unit
app.get('/question1', async (req, res) => {
    try {
            // We will default to polling_unit_uniqueid = 8 based on the test hint
                    // But allowing a user to check other units by adding ?id=X to the URL
                            const puId = req.query.id || 8; 
                                    
                                            // Execute the SQL Query
                                                    const [results] = await pool.query(
                                                                'SELECT party_abbreviation, party_score FROM announced_pu_results WHERE polling_unit_uniqueid = ?', 
                                                                            [puId]
                                                                                    );
                                                                                            
                                                                                                    // Render the EJS file and pass the database results into it
                                                                                                            res.render('question1', { results: results, puId: puId });
                                                                                                                } catch (err) {
                                                                                                                        console.error(err);
                                                                                                                                res.status(500).send('Error fetching data from database');
                                                                                                                                    }
                                                                                                                                    });

                                                                                                                                    // Question 2: Display summed total results for a selected LGA
                                                                                                                                    app.get('/question2', async (req, res) => {
                                                                                                                                        try {
                                                                                                                                                // 1. Fetch all LGAs to populate the dropdown select box
                                                                                                                                                        const [lgas] = await pool.query('SELECT lga_id, lga_name FROM lga');
                                                                                                                                                                
                                                                                                                                                                        let results = [];
                                                                                                                                                                                let selectedLga = req.query.lga_id;

                                                                                                                                                                                        // 2. If the user selected an LGA, calculate the sum of all its polling units
                                                                                                                                                                                                if (selectedLga) {
                                                                                                                                                                                                            const sumQuery = `
                                                                                                                                                                                                                            SELECT party_abbreviation, SUM(party_score) as total_score 
                                                                                                                                                                                                                                            FROM announced_pu_results 
                                                                                                                                                                                                                                                            JOIN polling_unit ON announced_pu_results.polling_unit_uniqueid = polling_unit.uniqueid 
                                                                                                                                                                                                                                                                            WHERE polling_unit.lga_id = ? 
                                                                                                                                                                                                                                                                                            GROUP BY party_abbreviation
                                                                                                                                                                                                                                                                                                        `;
                                                                                                                                                                                                                                                                                                                    const [summedData] = await pool.query(sumQuery, [selectedLga]);
                                                                                                                                                                                                                                                                                                                                results = summedData;
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                // 3. Render the page with the data
                                                                                                                                                                                                                                                                                                                                                        res.render('question2', { lgas: lgas, results: results, selectedLga: selectedLga });
                                                                                                                                                                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                    console.error(err);
                                                                                                                                                                                                                                                                                                                                                                            res.status(500).send('Error fetching data for Question 2');
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                });
                                                            
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                // Question 3: Render the Form
                                                                                                                                                                                                                                                                                                                                                                                app.get('/question3', (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                    res.render('question3');
                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                    // Question 3: Handle the Form Submission and Insert into Database
                                                                                                                                                                                                                                                                                                                                                                                    app.post('/question3', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                const { pu_id, PDP, DPP, ACN, PPA, CDC, JP } = req.body;
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                // Group the scores into an object
                                                                                                                                                                                                                                                                                                                                                                                                                        const partyScores = { PDP, DPP, ACN, PPA, CDC, JP };
                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                        const user = 'Riskiyat Adejumoke'; // Signature in the DB
                                                                                                                                                                                                                                                                                                                                                                                                                                                const date = new Date();
                                                                                                                                                                                                                                                                                                                                                                                                                                                        const ip = req.ip || '192.168.1.1';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Loop through the object and insert a row for each party's score
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (const [party, score] of Object.entries(partyScores)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await pool.query(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'INSERT INTO announced_pu_results (polling_unit_uniqueid, party_abbreviation, party_score, entered_by_user, date_entered, user_ip_address) VALUES (?, ?, ?, ?, ?, ?)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [pu_id, party, score, user, date, ip]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Re-render the form with a success message
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.render('question3', { success: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error(err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.status(500).send('Error saving results to the database');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                         app.listen(3000, () => {
                                                          console.log('Server is running on port 3000');
                                                          });
module.exports = app;
